services:
  sqlite-server:
    image: your-custom-sqlite-server-image
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      SQLITE_DB_PATH: "/data/mydatabase.db"
  admin:
    image:
