version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: balltrap
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
