name: balltrap
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.10

  riverpod_annotation: ^2.3.4
  cupertino_icons: ^1.0.2
  drag_and_drop_lists: ^0.3.3
  nfc_manager: ^3.3.0
  uuid: ^4.3.3
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.0
  mysql_client: ^0.0.27
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.2
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/animations/
flutter_launcher_icons:
  android: "balltrap"
  image_path: "assets/images/icon.png"
  ios: false
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
